spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nizzi?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: ''
    tomcat:                     # Keep the connection alive if idle for a long time (needed in production)
      test-while-idle: true
      validate-query: SELECT 1
  jpa:
    generate-ddl: true
    show-sql: true              # Show or not log for each sql query
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dial
    hibernate:
      ddl-auto: update          # Schema will be automatically updated accordingly to java entities found
