spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    password: ''
    url: jdbc:mysql://localhost:3306/nizzi?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
